config/routes.rb
Rails.application.routes.draw do
  get 'lectures/index'
  get 'lectures/new'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'posts/index'
  root 'posts#index'

  resources :posts, only: [:index]
  resources :users, only: [:show]

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
    resources :reviews, only: [:create]

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

end

app/models/lecture.rb
class Lecture < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy

    has_many :post_tags, dependent: :destroy
    has_many :tags, through: :post_tags
    has_many :reviews, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :reviews, dependent: :destroy
    mount_uploader :image, ImageUploader
    
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :post_tags, dependent: :destroy
    has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy

  has_many :reviews, dependent: :destroy

  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
    before_action :configure_permitted_parameters, if: :devise_controller?

    protect_from_forgery
   
    protected
    
    def configure_permitted_parameters
  
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      post = Post.find(params[:post_id])
      comment = post.comments.build(comment_params) 
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) 
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) 
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
      
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
    def index
     @lectures = Lecture.all
    end
  
    def new
      @lecture = Lecture.new
    end
  
    def create
      @lecture = Lecture.new(lecture_params)
  
      if @lecture.save 
        redirect_to action: 'index'
      else 
        redirect_to action: 'new'
      end
    end
  
  
  
    private
  
    def lecture_params
      params.require(:lecture).permit(:level)
    end
  end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(post_id: params[:post_id])
        redirect_back(fallback_location: root_path)
    end
    
      def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    before_action :store_user_location!, if: :storable_location?
    # before_action :authenticate_user!
    def index

      if params[:search] == nil
        @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
      elsif params[:search] == ''
        @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
      else
        @posts = Post.where("body LIKE ? ",'%' + params[:search] + '%')
      end
      # @posts = @posts.page(params[:page]).per(9)
      
    end
      
    def new
      @post = Post.new
    end
      
    def create

      post = Post.new(post_params)
      post.user_id = current_user.id

      if post.save!
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
    end
      
    def show
      @post = Post.find(params[:id])
      @comments = @post.comments
      @comment = Comment.new
      @reviews = @post.reviews
      @review = Review.new
    end
      
    def edit
       @post = Post.find(params[:id])
    end
      
    def update
       post = Post.find(params[:id])
      if post.update(post_params)
        redirect_to :action => "show", :id => post.id
      else
        redirect_to :action => "new"
      end
    end
      
    def destroy
       post = Post.find(params[:id])
       post.destroy
       redirect_to action: :index
    end
      
    private
    def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr? 
    end

    def store_user_location!
      store_location_for(:user, request.fullpath)
    end

    def after_sign_in_path_for(resource_or_scope)
      stored_location_for(resource_or_scope) || super
    end
    def post_params
      params.require(:post).permit(:body, :body2, :body3, :body4, :body5, :body6,:body7, :image, :level, :tag_ids,:lat,:lng,:wifi,:outlet)
    end
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
        before_action :authenticate_user!
      
        def create
          @post = Post.find(params[:post_id])
          review = @post.reviews.build(review_params) 
          review.user_id = current_user.id
          if review.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path)
          else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path)
          end
        end
      
        private
      
          def review_params
            params.require(:review).permit(:eve, :content)
          end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
        :user
     end
     
     def resource
        @resource ||= User.new
     end
     
     def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
     end
     
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
    end
     
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
    end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lectures/index.html.erb
<h1>Lectures#index</h1>
<p>Find me in app/views/lectures/index.html.erb</p>

app/views/lectures/new.html.erb
<h1>Lectures</h1>
<p>Find me in app/views/lectures/new.html.erb</p>

app/views/posts/edit.html.erb
<div class="new">

<%# <div class="new-title">カフェ登録</div> %>

<%= form_for @post do |f| %>

<div class="new-container">

    <div class="new-subtitle">Basic Information</div>

    <div class="new-list">

        <div class="new-listtop"><p><%= f.label :店名 %></p></div>
        <%= f.text_field :body %>

        <p><%= f.label :アクセス %></p>
        <%= f.text_field :body2 %>

        <p><%= f.label :営業時間 %></p>
        <%= f.text_field :body3 %>

        <p><%= f.label :定休日 %></p>
        <%= f.text_field :body4 %>

        <p><%= f.label :"Hp" %></p>
        <%= f.text_field :body5 %>

        <p><%= f.label :twitter %></p>
        <%= f.text_field :body6 %>

        <p><%= f.label :instagram %></p>
        <%= f.text_field :body7 %>

    </div>

</div>

<div class="new-container">

    <div class="new-subtitle">Cover Photo</div>
    <div class="new-coverphoto">
    <%= f.file_field :image %> 
    </div>

</div>

<div class="new-container">

    <div class="new-subtitle">Google Map</div>

    <div class="new-attention">
    検索ボタンを押し、Google Map上で正しい位置が表示されていることを確認してください。
    </div>

    <div class="new-cafename">
    <p><%= f.label :店名 %></p>
    <input class="new-cafename1" id="address" type="textbox" value="" >
    <input class="new-cafename2" type="button" value="検索" onclick="codeAddress()">
    </div>

    <div class="new-googlemap">
    
        <div  id='map'></div>
    
        <style>
        #map {
            height: 300px;
            width: 100%%;
        }
        </style>
    
        <script>
        //初期マップの設定
        let map
        let marker
        function initMap(){
            geocoder = new google.maps.Geocoder()
            map = new google.maps.Map(document.getElementById('map'), {
            center:  {lat: 35.6803997, lng:139.7690174},  //東京
            zoom: 15,
            });
        }
    
        //検索後のマップ作成
        let geocoder
        let aft
        function codeAddress(){
        let inputAddress = document.getElementById('address').value;
        geocoder.geocode( { 'address': inputAddress}, function(results, status) {
        if (status == 'OK') {
            //マーカーが複数できないようにする
            if (aft == true){
                marker.setMap(null);
            }
    
            //新しくマーカーを作成する
            map.setCenter(results[0].geometry.location);
                marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location,
                draggable: true	// ドラッグ可能にする
            });
    
            //二度目以降か判断
            aft = true
    
            //検索した時に緯度経度を入力する
            document.getElementById('lat').value = results[0].geometry.location.lat();
            document.getElementById('lng').value = results[0].geometry.location.lng();
    
            // マーカーのドロップ（ドラッグ終了）時のイベント
            google.maps.event.addListener( marker, 'dragend', function(ev){
                // イベントの引数evの、プロパティ.latLngが緯度経度
                document.getElementById('lat').value = ev.latLng.lat();
                document.getElementById('lng').value = ev.latLng.lng();
            });
        } else {
            alert('該当する結果がありませんでした：' + status);
        }
        });   
        }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBadobo2NJ9FUPJOJukDECqY4aqfxIlKjY&callback=initMap" async defer></script>

        <div class="new-latlng">
            <%= f.text_field :lat,:value =>"", id: :lat %>
            <%= f.text_field :lng,:value =>"", id: :lng %>
        </div>

    </div>

</div>

<div class="new-submit">
    <%= form_with(model: @post, local: true) do |f| %>
        <%= f.submit '編集' %>
    <% end %>
</div>

</div>

<% end %>

</div>

app/views/posts/index.html.erb
<div class="top">

    <div class="top2">

        <p> カフェを検索する</p>

        <div class="top-search">
            <form class="top-search2" action="/posts/index" accept-charset="UTF-8" method="get">
                <label><input type="text" name="search" id="search"></label>
                <button type="submit" name="commit" data-disable-with="検索"></button>
            </form>
        </div>

        <div class="top2-newcafe"><%= link_to "カフェ登録はこちら", new_post_path %></div>

    </div>

<div class="top-catchphrase">
  <div class="p1">
    <p>カフェで</p>
    <p>快適な作業をしたい、</p>
  </div>
  <div class="p2">
    <p>あなたへ。</p>
  </div>
</div>

</div>

<div class="index">

    <%#= page_entries_info @posts %>

    <div class="posts-container">

        <% @posts.each do |t| %>
    
            <div class="post1">

                <%= link_to post_path(t.id) do %>
                    <%= image_tag t.image_url, size: "330x220" if t.image? %>                
                <% end %>

                <div class="post2">

                    <div class="post-list">
                        
                        <div class="post-list1">
                            <div class="post-wifi">
                                <p><i class="fa-solid fa-wifi"></i></p>
                                <p><%= t.wifi %></p>
                            </div>
                            <div class="post-outlet">
                                <p><i class="fa-solid fa-plug"></i></p>
                                <p><%= t.outlet %></p></p>
                            </div>
                        </div>
                    

                        <div class="post-list2">

                                        <% if user_signed_in? %>

                                            <% if current_user.already_liked?(t) %>
                                                <%= button_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                                                    <i class="fa-solid fa-bookmark"></i>
                                                <% end %>

                                            <% else %>

                                                <%= button_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                                                    <i class="fa-regular fa-bookmark"></i>
                                                <% end %>

                                            <% end %>

                                        <% else %>
                                        
                                            <i class="fa-regular fa-bookmark"></i>

                                        <% end %>
                        </div>

                    </div>

                

                    <div class="post-cafename"><%= link_to t.body, post_path(t.id) %></div>
                
                </div>
                
                <%#= link_to "詳細", post_path(t.id) %>

            </div>

        <% end %>

    </div>

    <%#= paginate @posts %>

</div>

app/views/posts/new.html.erb
<div class="new">

<%# <div class="new-title">カフェ登録</div> %>

<%= form_for @post do |f| %>

<div class="new-container">

    <div class="new-subtitle">Basic Information</div>

    <ol class="timeline-003">
    <li class="current">step1</li>
    <li>step2</li>
    <li>step3</li>
    </ol>

    <div class="new-list">

        <div class="new-listtop"><p><%= f.label :店舗名 %></p></div>
        <%= f.text_field :body , placeholder:" スターバックスコーヒー アトレ恵比寿店" %>

        <p><%= f.label :アクセス %></p>
        <%= f.text_field :body2, placeholder:"  恵比寿駅 徒歩1分" %>

        <p><%= f.label :営業時間 %></p>
        <%= f.text_field :body3, placeholder:"  7:00 - 22:30" %>

        <p><%= f.label :定休日 %></p>
        <%= f.text_field :body4, placeholder:"  不定休" %>

        <div class="new-listhp"><p><%= f.label :HP %></p></div>
        <%= f.text_field :body5, placeholder:"  https://store.starbucks.co.jp/detail-552/"  %>

        <p><%= f.label :twitter %></p>
        <%= f.text_field :body6 %>

        <p><%= f.label :instagram %></p>
        <%= f.text_field :body7 %>

        <p>Wi-Fi</p>
        <div class="new-wifi">
            <%= f.radio_button :wifi, "有" %>
            <div class="new-wifi-name">有</div>
            <%= f.radio_button :wifi, "無" %>
            <div class="new-wifi-name">無</div>
        </div>

        <p>コンセント</p>
        <div class="new-outlet">
              <%= f.radio_button :outlet, "有" %>
            <div class="new-wifi-name">有</div>
            <%= f.radio_button :outlet, "無" %>
            <div class="new-wifi-name">無</div>
        </div>

    </div>

</div>

<div class="new-container">

    <div class="new-subtitle">Cover Photo</div>

    <ol class="timeline-003">
    <li class="prev">step1</li>
    <li class="current">step2</li>
    <li>step3</li>
    </ol>

    <div class="new-coverphoto">
    <%= f.file_field :image %> 
    </div>

</div>

<div class="new-container">

    <div class="new-subtitle">Google Map</div>

    <ol class="timeline-003">
    <li class="prev">step1</li>
    <li class="prev">step2</li>
    <li class="current">step3</li>
    </ol>

    <div class="new-attention">
    検索ボタンを押し、Google Map上で正しい位置が表示されていることを確認してください。
    </div>

    <div class="new-cafename">
    <input class="new-cafename1" id="address" type="textbox" value="" placeholder="  店舗名" >
    <input class="new-cafename2" type="button" value="検索" onclick="codeAddress()">
    </div>

    <div class="new-googlemap">
    
        <div  id='map'></div>
    
        <style>
        #map {
            height: 300px;
            width: 100%%;
        }
        </style>
    
        <script>
        //初期マップの設定
        let map
        let marker
        function initMap(){
            geocoder = new google.maps.Geocoder()
            map = new google.maps.Map(document.getElementById('map'), {
            center:  {lat: 35.6803997, lng:139.7690174},  //東京
            zoom: 15,
            });
        }
    
        //検索後のマップ作成
        let geocoder
        let aft
        function codeAddress(){
        let inputAddress = document.getElementById('address').value;
        geocoder.geocode( { 'address': inputAddress}, function(results, status) {
        if (status == 'OK') {
            //マーカーが複数できないようにする
            if (aft == true){
                marker.setMap(null);
            }
    
            //新しくマーカーを作成する
            map.setCenter(results[0].geometry.location);
                marker = new google.maps.Marker({
                map: map,
                position: results[0].geometry.location,
                draggable: true	// ドラッグ可能にする
            });
    
            //二度目以降か判断
            aft = true
    
            //検索した時に緯度経度を入力する
            document.getElementById('lat').value = results[0].geometry.location.lat();
            document.getElementById('lng').value = results[0].geometry.location.lng();
    
            // マーカーのドロップ（ドラッグ終了）時のイベント
            google.maps.event.addListener( marker, 'dragend', function(ev){
                // イベントの引数evの、プロパティ.latLngが緯度経度
                document.getElementById('lat').value = ev.latLng.lat();
                document.getElementById('lng').value = ev.latLng.lng();
            });
        } else {
            alert('該当する結果がありませんでした：' + status);
        }
        });   
        }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBadobo2NJ9FUPJOJukDECqY4aqfxIlKjY&callback=initMap" async defer></script>

        <div class="new-latlng">
            <%= f.text_field :lat,:value =>"", id: :lat %>
            <%= f.text_field :lng,:value =>"", id: :lng %>
        </div>

    </div>

</div>

<div class="new-submit">
    <%= form_with(model: @post, local: true) do |f| %>
        <%= f.submit '投稿' %>
    <% end %>
</div>

</div>

<% end %>

</div>

app/views/posts/show.html.erb
<div class="show">

    <div class="show-cafename">
        <%= @post.body %>
           <div class="show-book">

            <% if user_signed_in? %>
                <% if current_user.already_liked?(@post) %>
                    <%= button_to post_like_path(@post), method: :delete do %>
                        <i class="fa-solid fa-bookmark"></i>
                    <% end %>
                <% else %>
                    <%= button_to post_likes_path(@post), method: :post do %>
                        <i class="fa-regular fa-bookmark"></i>
                    <% end %>
                <% end %>
            <% else %>
                <i class="fa-regular fa-bookmark"></i>
            <% end %>

        </div>
    </div>

        <div class="show-list">
            <%= link_to "編集", edit_post_path(@post.id) %>
            <%= link_to "削除", post_path(@post.id), method: :delete %>
            最終更新日：<%= @post.created_at %>
        </div>

        <div class="show-informations">

            <h3>基本情報</h3>
                
            <div class="show-information1">
                <div class="show-information2">アクセス</div>
                <p><%= @post.body2 %></p>
            </div>

            <div class="show-information1">
                <div class="show-information2">営業時間</div>
                <p><%= @post.body3 %></p>
            </div>

            <div class="show-information1">
                <div class="show-information2">定休日</div>
                <p><%= @post.body4 %></p>
            </div>

            <div class="show-information1">
                <div class="show-information2">HP</div>
                <p><%= @post.body5 %></p>
            </div>

            <div class="show-information1">
                <div class="show-information2">Twitter</div>
                <p><%= @post.body6 %></p>
            </div>

            <div class="show-information1">
                <div class="show-information2">Instagram</div>
                <p><%= @post.body7 %></p>
            </div>

            <div class="show-information1">
                <div class="show-information2">Wi-Fi</div>
                <p><%= @post.wifi %></p>
            </div>

            <div class="show-information1">
                <div class="show-information2">コンセント</div>
                <p><%= @post.outlet %></p>
            </div>

            <div class="show-googlemap">

                <div id='map'></div>

                <style>
                #map {
                width: 280px; height: 410px;
                }
                </style>

                <!-- js部分 -->
                <script>
                //初期マップの設定
                let map
                let marker
                function initMap(){
                geocoder = new google.maps.Geocoder()

                map = new google.maps.Map(document.getElementById('map'), {
                    center:  {lat: <%= @post.lat %>, lng: <%= @post.lng %>},
                    zoom: 15,
                });

                marker = new google.maps.Marker({
                    position:  {lat: <%= @post.lat %>, lng: <%= @post.lng %>},
                    map: map
                });
                }
                </script>

                <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBadobo2NJ9FUPJOJukDECqY4aqfxIlKjY&callback=initMap" async defer></script>
    
            </div>

        </div>
        

    
    

    <div class="comment-wrapper">

        <h3>口コミ一覧</h3>

        <div class="show-reviews">
                
            <% @reviews.each do |c| %>

                <div class="show-review">

                    <div class="show-review1">

                        <div><i class="fa-regular fa-circle-user"></i></div>
                        <div class="show-review-name"><%= c.user.name unless c.user.blank? %></div>

                        <div>
                        <span class="star-rating">
                            <span class="star-rating-front" style="width: <%= getPercent(c.eve) %>%;">★★★★★</span>
                            <span class="star-rating-back">★★★★★</span>
                        </span> 
                        </div>
                        
                    </div>

                    <%= c.content%>

                </div>
        
            <% end %>

        </div>

    </div>


</div>



<div class="new2">

<div class="new2-container">

<div class="review-wrapper">

<% if user_signed_in? %>
    
    <%= form_with(model: [@post, @review], local: true) do |f| %>

        <h4>新規口コミ</h4>

        <div class="post_form">
            <%= f.radio_button :eve,  5 ,id: 'star6'%>
            <label for="star6"><span class="text"></span>★</label>

            <%= f.radio_button :eve,  4 ,id: 'star7'%>
            <label for="star7"><span class="text"></span>★</label>

            <%= f.radio_button :eve, 3 ,id: 'star8'%>
            <label for="star8"><span class="text"></span>★</label>

            <%= f.radio_button :eve, 2 ,id: 'star9'%>
            <label for="star9"><span class="text"></span>★</label>

            <%= f.radio_button :eve, 1 ,id: 'star10'%>
            <label for="star10"><span class="text"></span>★</label>
        </div>

        <div class="new2-comment">
            <%= f.text_area :content %>
                <div class="new2-comment-button">
                <%= button_tag type: "submit" do %>
                    <i class="fa-regular fa-comment"></i> 投稿
                <% end %>
            </div>
        </div>

    <% end %>

<% end %>

</div>
    
</div>    

</div>