config/routes.rb
Rails.application.routes.draw do
  get 'lectures/index'
  get 'lectures/new'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'posts/index'
  root 'posts#index'

  resources :posts, only: [:index]
  resources :users, only: [:show]

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
    resources :reviews, only: [:create]

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

end

app/models/lecture.rb
class Lecture < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy

    has_many :post_tags, dependent: :destroy
    has_many :tags, through: :post_tags
    has_many :reviews, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :reviews, dependent: :destroy
    mount_uploader :image, ImageUploader
    
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :post_tags, dependent: :destroy
    has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy

  has_many :reviews, dependent: :destroy

  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(post_id: params[:post_id])
        redirect_back(fallback_location: root_path)
    end
    
      def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    before_action :store_user_location!, if: :storable_location?
    # before_action :authenticate_user!
    def index

      if params[:search] == nil
        @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
      elsif params[:search] == ''
        @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
      else
        @posts = Post.where("body LIKE ? ",'%' + params[:search] + '%')
      end
      # @posts = @posts.page(params[:page]).per(9)
      
    end
      
    def new
      @post = Post.new
    end
      
    def create

      post = Post.new(post_params)
      post.user_id = current_user.id

      if post.save!
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
    end
      
    def show
      @post = Post.find(params[:id])
      @comments = @post.comments
      @comment = Comment.new
      @reviews = @post.reviews
      @review = Review.new
    end
      
    def edit
       @post = Post.find(params[:id])
    end
      
    def update
       post = Post.find(params[:id])
      if post.update(post_params)
        redirect_to :action => "show", :id => post.id
      else
        redirect_to :action => "new"
      end
    end
      
    def destroy
       post = Post.find(params[:id])
       post.destroy
       redirect_to action: :index
    end
      
    private
    def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr? 
    end

    def store_user_location!
      store_location_for(:user, request.fullpath)
    end

    def after_sign_in_path_for(resource_or_scope)
      stored_location_for(resource_or_scope) || super
    end
    def post_params
      params.require(:post).permit(:body, :body2, :body3, :body4, :body5, :body6,:body7, :image, :level, :tag_ids,:lat,:lng,:wifi,:outlet)
    end
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
        before_action :authenticate_user!
      
        def create
          @post = Post.find(params[:post_id])
          review = @post.reviews.build(review_params) 
          review.user_id = current_user.id
          if review.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path)
          else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path)
          end
        end
      
        private
      
          def review_params
            params.require(:review).permit(:eve, :content)
          end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
        :user
     end
     
     def resource
        @resource ||= User.new
     end
     
     def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
     end
     
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
    end
     
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
    end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Original</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/8d5fcc9eb8.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
  
    <header>

    <div class="header-title">
        <a href="/">nomadcafe</a>
    </div>

    <div class="header-list">
        
        <% if user_signed_in? %>
            
            <%= link_to "mypage" , user_path(current_user.id) %>
            <%= link_to "sign out", destroy_user_session_path, method: :delete %>

        <% else %>

    
        <div data-micromodal-trigger="modal-1">
            sign in
        </div>

        <div class="modal" id="modal-1" aria-hidden="true">
            <div class="modal-overlay" data-micromodal-close>
                <div class="modal-container">
                    <div class="modal-content">
                    
                        <p>sign in</p>
                        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                            <div class="field-1">
                                <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "  e-mail"%>
                            </div>
                            <div class="field-2">
                                <%= f.password_field :password, autocomplete: "current-password", placeholder: "  password" %>
                            </div>
                            <% if devise_mapping.rememberable? %>
                                <div class="field-3">
                                    <%= f.check_box :remember_me %>
                                    <%= f.label :"情報を保存する" %>
                                </div>
                            <% end %>
                            <div class="top-actions">
                                <%= f.submit "sign in" %>
                            </div>
                        <% end %>
                        <div class="top-registrations">
                            <%= render "users/shared/links" %>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <% end %>
        
    </div>

    </header>
    
    <main>
      <%= yield %>
    </main>

    <footer>
      <p>Copyright © GeekSalon All Rights Reserved.</p>
    </footer>

    <script src="https://unpkg.com/micromodal/dist/micromodal.min.js"></script>
  </body>

</html>